export enum Muscles {
  CALVES = "calves",
  QUADS = "quads",
  ABDOMINALS = "abdominals",
  OBLIQUES = "obliques",
  HANDS = "hands",
  FOREARMS = "forearms",
  BICEPS = "biceps",
  FRONT_SHOULDERS = "front-shoulders",
  CHEST = "chest",
  TRAPS = "traps",
  HAMSTRINGS = "hamstrings",
  GLUTES = "glutes",
  TRICEPS = "triceps",
  LATS = "lats",
  LOWER_BACK = "lowerback",
  TRAPS_MIDDLE = "traps-middle",
  REAR_SHOULDERS = "rear-shoulders",
}
